#!/bin/sh

composer install --optimize-autoloader
npm install && npm run production

# database
php artisan migrate:fresh --database=mysql --path=database/migrations/mysql/ --seed
php artisan migrate --path=database/migrations/nonsql

# Lavara config
php artisan storage:link \
  && php artisan config:cache \
  && php artisan route:cache \
  && php artisan optimize

# permissions for scripts
chmod +x ./docker/web/*

# up
php artisan up